# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmvp" do
  name "cmvp"
  desc "Terminal UI for searching NIST CMVP validated cryptographic modules"
  homepage "https://github.com/ethanolivertroy/cmvp-tui"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmvp"

  on_macos do
    on_intel do
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v#{version}/cmvp-darwin-amd64.tar.gz"
      sha256 "2be991189fd25f8ee01151155b1720e09ac30a912079c56c56e75de4697b8cad"
    end
    on_arm do
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v#{version}/cmvp-darwin-arm64.tar.gz"
      sha256 "3a45f9249d9905e2193b23d5cfd2aa6203e8ba945f2556b042276f5ba6d8f409"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v#{version}/cmvp-linux-amd64.tar.gz"
      sha256 "b5c72e00bd29ab5a8e4017137f6105bf06c981e21424d80b6e9cba50f18f9f07"
    end
    on_arm do
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v#{version}/cmvp-linux-arm64.tar.gz"
      sha256 "79a6672bdb5dbfcdb400ec11373b88a8147e5734ca7a4352e07e0a62059a61b0"
    end
  end

  # No zap stanza required
end
