# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmvp" do
  name "cmvp"
  desc "Terminal UI for searching NIST CMVP validated cryptographic modules"
  homepage "https://github.com/ethanolivertroy/cmvp-tui"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmvp"

  on_macos do
    on_intel do
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v#{version}/cmvp-darwin-amd64.tar.gz"
      sha256 "77de86aa28a42c80f80e69a0f5f98b080f47bbad7460ee8e142071b40c24fa61"
    end
    on_arm do
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v#{version}/cmvp-darwin-arm64.tar.gz"
      sha256 "c97d70807d7f617b1ef9d2b08de68bfa960748ff841f720a1e6442da43ce6226"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v#{version}/cmvp-linux-amd64.tar.gz"
      sha256 "b350f237fdf34a257c34b4eb61f91f1db4e7b8c764171eedd64d8d31fd651a8b"
    end
    on_arm do
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v#{version}/cmvp-linux-arm64.tar.gz"
      sha256 "8692b773aa3ff857949c806ff08ee691403a72d3c249746285ebdc021d2148b5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmvp"]
    end
  end

  # No zap stanza required
end
