# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmvp < Formula
  desc "Terminal UI for searching NIST CMVP validated cryptographic modules"
  homepage "https://github.com/ethanolivertroy/cmvp-tui"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v0.1.1/cmvp-darwin-amd64.tar.gz"
      sha256 "8334a7a464e291ffdfd1a266c31553df6e94c4ae80f17d45f0eedeab3bbcb7dd"

      def install
        bin.install "cmvp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v0.1.1/cmvp-darwin-arm64.tar.gz"
      sha256 "60d48506a5e5fc94414306d707a1d59d556f3041f977cbae76d35a8952fd876c"

      def install
        bin.install "cmvp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v0.1.1/cmvp-linux-amd64.tar.gz"
      sha256 "3ab459a9561afe028cf9b07549f4dbf3034634b55c8e9f32bacdbefeda00860d"
      def install
        bin.install "cmvp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v0.1.1/cmvp-linux-arm64.tar.gz"
      sha256 "dcca29fff7e5e9337c85f91d2e975aecb3e7b8aba42a23000a678177b074cf26"
      def install
        bin.install "cmvp"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cmvp --version")
  end
end
