# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmvp < Formula
  desc "Terminal UI for searching NIST CMVP validated cryptographic modules"
  homepage "https://github.com/ethanolivertroy/cmvp-tui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v0.1.0/cmvp-darwin-amd64.tar.gz"
      sha256 "23876c45a96f2a4f0bf559a2217e5cf449f3ebfbabfafdcc74ae01a82901c38c"

      def install
        bin.install "cmvp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v0.1.0/cmvp-darwin-arm64.tar.gz"
      sha256 "0345a3dcee8b60547d054daaeae9dec3d1ebe33389d930b0dc17ee283a76d735"

      def install
        bin.install "cmvp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v0.1.0/cmvp-linux-amd64.tar.gz"
      sha256 "34f820d24c95cca4db509d99e4565fa04598049c0da14abbfa1c9b0bebbfeedc"
      def install
        bin.install "cmvp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/cmvp-tui/releases/download/v0.1.0/cmvp-linux-arm64.tar.gz"
      sha256 "5f4b3ee279865696fa608310b87a672a71faa49cba56907a316f2fb3370c3963"
      def install
        bin.install "cmvp"
      end
    end
  end

  test do
    assert_match "CMVP", shell_output("#{bin}/cmvp --help 2>&1", 1)
  end
end
