# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FedrampTui < Formula
  desc "Terminal UI for browsing FedRAMP documentation"
  homepage "https://github.com/ethanolivertroy/fedramp-tui"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-tui-darwin-amd64"
      sha256 "967fe131b7603edd0098e60cc7f3d1a8e84833f9cecc726bf728a66b1ed88fc6"

      def install
        bin.install "fedramp-tui-darwin-amd64" => "fedramp-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-tui-darwin-arm64"
      sha256 "d7cd6fb78f7f6b48cc6d2b11c2c55fccadd6e6f17e54ef2d67336d9bd29f9340"

      def install
        bin.install "fedramp-tui-darwin-arm64" => "fedramp-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-tui-linux-amd64"
      sha256 "98d531212782be179e74b809a46eff151251b484fe34fc4c0a0b578951ccede9"
      def install
        bin.install "fedramp-tui-linux-amd64" => "fedramp-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-tui-linux-arm64"
      sha256 "c22d9faf6492f850cc90b255533b6262ce2160c119fc2aee92b21a808413cf98"
      def install
        bin.install "fedramp-tui-linux-arm64" => "fedramp-tui"
      end
    end
  end

  test do
    system "#{bin}/fedramp-tui", "--help"
  end
end
