# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fedramp < Formula
  desc "Terminal UI for browsing FedRAMP authorized cloud services"
  homepage "https://github.com/ethanolivertroy/fedramp-tui"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.2/fedramp-darwin-amd64.tar.gz"
      sha256 "49e55a2f40b5f7f6c68d2efdf76297a1a76655955ecf0ac47a6ae31b2af21773"

      def install
        bin.install "fedramp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.2/fedramp-darwin-arm64.tar.gz"
      sha256 "60b656acf180d6c40dbe55c738b1a34f7fb2dd61851ce2ed905fab3204feea12"

      def install
        bin.install "fedramp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.2/fedramp-linux-amd64.tar.gz"
      sha256 "2987d8e780c193af002719143232dc8ba2008f8cfebebc2a7f0a36cbdbaa53bb"
      def install
        bin.install "fedramp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.2/fedramp-linux-arm64.tar.gz"
      sha256 "caa166fa2a13c946b22a2cb92d79868a1b95a44083cb48f81909299f84c9cc09"
      def install
        bin.install "fedramp"
      end
    end
  end

  test do
    assert_match "FedRAMP", shell_output("#{bin}/fedramp --help 2>&1", 1)
  end
end
