# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FedrampTui < Formula
  desc "Terminal UI for browsing FedRAMP documentation"
  homepage "https://github.com/ethanolivertroy/fedramp-tui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.0/fedramp-tui-darwin-amd64"
      sha256 "48bf78a7f045fc11c33d46fe8d31338226ff6b33dcb7c93fd4ad9e7ad227eb6d"

      def install
        bin.install "fedramp-tui-darwin-amd64" => "fedramp-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.0/fedramp-tui-darwin-arm64"
      sha256 "7d8b77d21ab3021bfc87d3a2cce281bdecc4d9dbb6d666b12d9b88840d658aa9"

      def install
        bin.install "fedramp-tui-darwin-arm64" => "fedramp-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.0/fedramp-tui-linux-amd64"
      sha256 "1d51919285f1ab2b4e7f546aaa786143ef375edc04d49d405a7f3751295cc1f6"
      def install
        bin.install "fedramp-tui-linux-amd64" => "fedramp-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.0/fedramp-tui-linux-arm64"
      sha256 "43cb1d2d505a6a1693ef70635564bb6d825e632100d7768990fde97cce8516d8"
      def install
        bin.install "fedramp-tui-linux-arm64" => "fedramp-tui"
      end
    end
  end

  test do
    system "#{bin}/fedramp-tui", "--help"
  end
end
