# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fedramp < Formula
  desc "Terminal UI for browsing FedRAMP authorized cloud services"
  homepage "https://github.com/ethanolivertroy/fedramp-tui"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-darwin-amd64.tar.gz"
      sha256 "347746d40fc274f6e7f1f93cc6ddea8c5a8b144dddaa30ffb1231a762f819209"

      def install
        bin.install "fedramp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-darwin-arm64.tar.gz"
      sha256 "3c697b71428bd37b8c6d32498564c482d35d95c598f841b2ecbf40248891e1ee"

      def install
        bin.install "fedramp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-linux-amd64.tar.gz"
      sha256 "df3f4ea98da069f5f7d576f017971f9d618909e762dfc04777fe0bd1249d25c1"
      def install
        bin.install "fedramp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-linux-arm64.tar.gz"
      sha256 "b2743aa359cb00fbe31b940e643cf170a7d31d960be57169710c2514bc7fa9fb"
      def install
        bin.install "fedramp"
      end
    end
  end

  test do
    assert_match "FedRAMP", shell_output("#{bin}/fedramp --help 2>&1", 1)
  end
end
