# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fedramp < Formula
  desc "Terminal UI for browsing FedRAMP authorized cloud services"
  homepage "https://github.com/ethanolivertroy/fedramp-tui"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-darwin-amd64.tar.gz"
      sha256 "39cebce30f3f5f96ca8882aaa91d4c8fc0869918ff8a5c51755dccd90a2ca016"

      def install
        bin.install "fedramp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-darwin-arm64.tar.gz"
      sha256 "8245514f83be82eca52948545fcba1273c375cd27ede21c3b8d86841cfcf308a"

      def install
        bin.install "fedramp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-linux-amd64.tar.gz"
      sha256 "e6daadc070006db4a146ce4c9c47f1dbd47425ec2605a43dd7d159c1289fa38d"
      def install
        bin.install "fedramp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/fedramp-tui/releases/download/v0.1.1/fedramp-linux-arm64.tar.gz"
      sha256 "88e801abc59bd09b8ea4bfa7ba5603d667574fc12e3ce684e702a757b7fa780d"
      def install
        bin.install "fedramp"
      end
    end
  end

  test do
    assert_match "FedRAMP", shell_output("#{bin}/fedramp --help 2>&1", 1)
  end
end
