# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KevsTui < Formula
  desc "Terminal UI for browsing CISA Known Exploited Vulnerabilities (KEV)"
  homepage "https://github.com/ethanolivertroy/kevs-tui"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/kevs-tui/releases/download/v0.1.1/kevs-tui-darwin-amd64.tar.gz"
      sha256 "2f6b641d4d9646a87e6ee457634fd3915e6a5a5af3a86f7c301029c26dfccafd"

      def install
        bin.install "kevs-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/kevs-tui/releases/download/v0.1.1/kevs-tui-darwin-arm64.tar.gz"
      sha256 "04223af757b54d8ab6415c977ccd7059943bc2709eea0298c7ecb67e1c016268"

      def install
        bin.install "kevs-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/kevs-tui/releases/download/v0.1.1/kevs-tui-linux-amd64.tar.gz"
      sha256 "58e531bd704f6da82c1fc235ca5457e79362e1133a20ed94ef29c18c01996e19"
      def install
        bin.install "kevs-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/kevs-tui/releases/download/v0.1.1/kevs-tui-linux-arm64.tar.gz"
      sha256 "0b67fb4d655be4c2126f7f38ad4fad9532ba9113bb4e71395f569bd6f4dc0aaa"
      def install
        bin.install "kevs-tui"
      end
    end
  end

  test do
    assert_match "KEV", shell_output("#{bin}/kevs-tui --help 2>&1", 1)
  end
end
