# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KevsTui < Formula
  desc "Terminal UI for browsing CISA Known Exploited Vulnerabilities (KEV)"
  homepage "https://github.com/ethanolivertroy/kevs-tui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/kevs-tui/releases/download/v0.1.0/kevs-tui-darwin-amd64.tar.gz"
      sha256 "f930c7d42430799df81866d87ce931064d11148a26690f88e8a751f41ad8e578"

      def install
        bin.install "kevs-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/kevs-tui/releases/download/v0.1.0/kevs-tui-darwin-arm64.tar.gz"
      sha256 "e4a8beeaec7491e175eb34b63c32fcaa237ffd5271bccd60f9e0571d20084e81"

      def install
        bin.install "kevs-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/kevs-tui/releases/download/v0.1.0/kevs-tui-linux-amd64.tar.gz"
      sha256 "d37f14ce1c68b6e1b109f3b8f422ce3ae0f6cac9700742df87356694b0ccd410"
      def install
        bin.install "kevs-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/kevs-tui/releases/download/v0.1.0/kevs-tui-linux-arm64.tar.gz"
      sha256 "31feb98df780d86b099711c3b346695bb9935f578c2551a7bf14f1ff773e64a6"
      def install
        bin.install "kevs-tui"
      end
    end
  end

  test do
    assert_match "KEV", shell_output("#{bin}/kevs-tui --help 2>&1", 1)
  end
end
