# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VantaExporter < Formula
  desc "CLI tool to export Vanta audit evidence organized by control"
  homepage "https://github.com/ethanolivertroy/vanta-go-export"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.0/vanta-exporter-darwin-amd64.tar.gz"
      sha256 "8cf4b3c17f4e1d5075caab23c5cdfe6ca4cd060d601a49a12a16d7a5f9622208"

      def install
        bin.install "vanta-exporter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.0/vanta-exporter-darwin-arm64.tar.gz"
      sha256 "4f5a10522637bc5c4ce731221d643e274278353214a5ba4d50c58ac67cefd246"

      def install
        bin.install "vanta-exporter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.0/vanta-exporter-linux-amd64.tar.gz"
      sha256 "d035087a1e9094754daa828411c8af753ff46822ab01ee39f0f4e1c45ab60f94"
      def install
        bin.install "vanta-exporter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.0/vanta-exporter-linux-arm64.tar.gz"
      sha256 "53459bc8c6497255409737ed4654b5986dafb7575a383e3ccf11c685a01bb84c"
      def install
        bin.install "vanta-exporter"
      end
    end
  end

  test do
    assert_match "vanta", shell_output("#{bin}/vanta-exporter --help 2>&1", 2)
  end
end
