# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VantaExporter < Formula
  desc "CLI tool to export Vanta audit evidence organized by control"
  homepage "https://github.com/ethanolivertroy/vanta-go-export"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.0/vanta-exporter-darwin-amd64.tar.gz"
      sha256 "5e08ced0c1a872fec037c0251d4f4e7fa6ac2ccd2531ab512139d22cde6eeed7"

      def install
        bin.install "vanta-exporter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.0/vanta-exporter-darwin-arm64.tar.gz"
      sha256 "ecea317ab6206954162af2d74dd04768fc91608cb214fe7a3126ed2178629caa"

      def install
        bin.install "vanta-exporter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.0/vanta-exporter-linux-amd64.tar.gz"
      sha256 "5a8c9b9dfebcea981c028898e8ddc67a5f44093ec8adc9092c91fc34f4215394"
      def install
        bin.install "vanta-exporter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.0/vanta-exporter-linux-arm64.tar.gz"
      sha256 "244f3b21cb69e20ec3cabbab438132d0b53de61faee3c567813e7dd7f1048270"
      def install
        bin.install "vanta-exporter"
      end
    end
  end

  test do
    assert_match "vanta", shell_output("#{bin}/vanta-exporter --help 2>&1", 2)
  end
end
