# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VantaExporter < Formula
  desc "CLI tool to export Vanta audit evidence organized by control"
  homepage "https://github.com/ethanolivertroy/vanta-go-export"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.2/vanta-exporter-darwin-amd64.tar.gz"
      sha256 "cabbb0f70c291a996c4fe47f4f57102519078fdf7987fd208bca77a5d71f3297"

      def install
        bin.install "vanta-exporter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.2/vanta-exporter-darwin-arm64.tar.gz"
      sha256 "7314c39be849ffcb253877baac32fed6a08953863f2021db6f73269a270a282c"

      def install
        bin.install "vanta-exporter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.2/vanta-exporter-linux-amd64.tar.gz"
      sha256 "56fdec255d8efeec3c13de5796036a987858d460ae6d1a4b0fa5006add689ab2"
      def install
        bin.install "vanta-exporter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ethanolivertroy/vanta-go-export/releases/download/v0.1.2/vanta-exporter-linux-arm64.tar.gz"
      sha256 "c517b762e14d16f55a0ced606bdf6626ea19dfedd794615cb2ae0178f3631497"
      def install
        bin.install "vanta-exporter"
      end
    end
  end

  test do
    assert_match "vanta", shell_output("#{bin}/vanta-exporter --help 2>&1", 2)
  end
end
